server:
  port: 9000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/sebastian.arismendy_/Documents/Sping-cloud/3.SpringCloudConfig
  security:
    user:
      name: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}

